services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npx mikro-orm migration:up && npm run start:dev"

  frontend:
    deploy:
      replicas: 0
